#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
//
// Web demo: a dependency-light HTTP bridge in front of grpc-pdf-inspector.
//
// There is only one request. The browser POSTs a PDF and reads Server-Sent
// Events off the *same* response, so the HTTP call has the same shape as the
// gRPC call underneath it: document bytes flowing one way while parse events
// flow the other.
//
// This service cannot emit anything until the upload is complete — a PDF's
// cross-reference table is its last bytes, so no page can be located before
// then. What the page shows instead is what happens the moment the last byte
// lands: `info` — the classification, the routing answer — in tens of
// milliseconds, long before any page is extracted, then each `page` of
// markdown as it is ready, an optional folded `document`, and `status` as
// the receipt.
//
//   node server.js            # http://127.0.0.1:8093
//
// Environment: PDF_ADDR (default 127.0.0.1:50067), PORT (default 8093),
// UI_BASE (default empty; serve everything under this path prefix instead).

import { createServer } from "node:http";
import { readFile, readdir, stat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { PdfClient, summarizeEvent } from "./lib/pdf.js";

const PORT = Number(process.env.PORT ?? 8093);
const ADDR = process.env.PDF_ADDR ?? "127.0.0.1:50067";
const client = new PdfClient(ADDR);
const publicDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "public");

/**
 * Path prefix the whole bridge is served under, e.g. `/ui/pdf` behind a
 * reverse proxy that forwards without stripping. Empty means the bridge
 * answers at the root, byte-for-byte as it always has.
 */
const UI_BASE = normalizeBase(process.env.UI_BASE ?? "");

function normalizeBase(base) {
  if (!base) return "";
  const withSlash = base.startsWith("/") ? base : `/${base}`;
  return withSlash.replace(/\/+$/, "");
}

/** Largest artificial delay accepted, in ms per chunk or per event. */
const MAX_DELAY_MS = 2000;

/**
 * Bytes per chunk fed into the gRPC call.
 *
 * The bridge re-slices the incoming body rather than forwarding whatever
 * Node's HTTP layer happened to hand it, because for a small PDF that is one
 * buffer, and a single chunk makes the upload bar invisible. Chunk size does
 * not change the events: chunks are concatenated before the document is
 * opened.
 */
const DEFAULT_CHUNK_BYTES = 4096;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/** Where the fixtures live. Resolved once, and used to bound path lookups. */
const sampleDir = path.resolve(publicDir, "..", "..", "sample-data");

/**
 * The fixtures, with their sizes, plus anything dropped in `sample-data/large`.
 *
 * The small `.pdf` files are generated by `scripts/make-samples.mjs` — this
 * repository commits no binaries. `large/` is gitignored and meant for real
 * documents worth megabytes, which do not belong in the repository either.
 */
async function listSamples() {
  const found = [];
  for (const dir of ["", "large"]) {
    const full = path.join(sampleDir, dir);
    let entries;
    try {
      entries = await readdir(full);
    } catch {
      continue; // `large/` is optional.
    }
    for (const entry of entries.filter((e) => e.endsWith(".pdf")).sort()) {
      const name = dir ? `${dir}/${entry}` : entry;
      const { size } = await stat(path.join(full, entry));
      found.push({ name, size });
    }
  }
  return found;
}

function sendJson(res, status, body) {
  res.writeHead(status, { "content-type": "application/json" });
  res.end(JSON.stringify(body));
}

/** Format one SSE event frame. */
function frame(event, data) {
  return `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
}

/** Mode names from the page's select, mapped to the contract's enum names. */
const MODES = {
  detect: "PROCESS_MODE_DETECT_ONLY",
  analyze: "PROCESS_MODE_ANALYZE",
  full: "PROCESS_MODE_FULL",
};

/**
 * Build PdfOptions from the query string.
 *
 * Every field is set explicitly rather than left absent, so the page's
 * controls mean exactly what they say and the wire never leans on the
 * contract's absent-means-default rules.
 */
function optionsFrom(url) {
  return {
    mode: MODES[url.searchParams.get("mode")] ?? "PROCESS_MODE_FULL",
    emitDocument: url.searchParams.has("document"),
  };
}

/**
 * Pipe one upload through ParsePdf, streaming events back on the same
 * response.
 *
 * `delayMs` sleeps between upload chunks, to make the upload bar visible on a
 * small local document. `paceMs` sleeps between events once extraction
 * begins; neither changes what the server does, only how much of it you get
 * to watch.
 */
async function bridge(req, res, url) {
  const options = optionsFrom(url);
  const delayMs = Math.min(Number(url.searchParams.get("delayMs") ?? 0) || 0, MAX_DELAY_MS);
  const paceMs = Math.min(Number(url.searchParams.get("paceMs") ?? 0) || 0, MAX_DELAY_MS);

  res.writeHead(200, {
    "content-type": "text/event-stream",
    "cache-control": "no-cache",
    connection: "keep-alive",
    // The page is watching for the first event; a proxy that buffers would
    // hide the only thing this demo exists to show.
    "x-accel-buffering": "no",
  });

  const call = client.openParse(options);
  let closed = false;

  const finish = () => {
    if (!closed) {
      closed = true;
      res.write(frame("done", {}));
      res.end();
    }
  };

  // Events are queued and written out one at a time, in stream order. The
  // queue is what the pace sleep and a slow browser push back against: past
  // the high-water mark the gRPC call is paused, and gRPC flow control
  // carries that back to the server, so a document is never held whole in
  // this process. grpc-js emits `end` as soon as the server half-closes, even
  // while paused with messages still buffered, so `end` cannot be used as
  // "the last event was written" — the sentinel in the same queue keeps the
  // ordering honest instead.
  const END = Symbol("end");
  const HIGH_WATER = 32;
  const LOW_WATER = 8;
  const queue = [];
  let pumping = false;

  const pump = async () => {
    if (pumping) return;
    pumping = true;
    while (queue.length > 0 && !closed) {
      const item = queue.shift();
      if (queue.length <= LOW_WATER) call.resume();
      if (item === END) {
        finish();
        break;
      }
      const summarized = summarizeEvent(item);
      if (summarized) {
        const [kind, data] = summarized;
        if (paceMs > 0) await sleep(paceMs);
        if (closed) break;
        if (!res.write(frame(kind, data))) {
          await new Promise((resolve) => {
            res.once("drain", resolve);
            res.once("close", resolve);
          });
        }
      }
    }
    pumping = false;
    if (queue.length > 0 && !closed) await pump();
  };

  // proto-loader's `oneofs: true` sets `message.event` to the name of the
  // active arm, so an arm this bridge has never heard of still forwards
  // rather than being dropped on the floor.
  call.on("data", (message) => {
    queue.push(message);
    if (queue.length > HIGH_WATER) call.pause();
    void pump();
  });
  call.on("error", (err) => {
    if (!closed) {
      closed = true;
      res.write(frame("grpc-error", { message: err.details ?? err.message }));
      res.end();
    }
  });
  call.on("end", () => {
    queue.push(END);
    void pump();
  });

  // If the browser goes away, stop parsing rather than finish into a void.
  res.on("close", () => {
    if (!closed) {
      closed = true;
      call.cancel();
    }
  });

  const chunkBytes = Math.max(
    1,
    Number(url.searchParams.get("chunkBytes") ?? 0) || DEFAULT_CHUNK_BYTES,
  );

  let fed = 0;
  try {
    for await (const buffer of req) {
      for (let at = 0; at < buffer.length; at += chunkBytes) {
        if (closed) break;
        const chunk = buffer.subarray(at, at + chunkBytes);
        call.write({ chunk });
        fed += chunk.length;
        // The page draws its upload bar from this, so it measures what the
        // server has actually been handed, not what the browser has queued.
        res.write(frame("fed", { bytes: fed }));
        if (delayMs > 0) await sleep(delayMs);
      }
      if (closed) break;
    }
    if (!closed) call.end();
  } catch {
    if (!closed) {
      closed = true;
      call.cancel();
      res.end();
    }
  }
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  // The router sees the path with the base stripped, so every route below is
  // written against the root and works identically with or without UI_BASE.
  let pathname = url.pathname;
  if (UI_BASE && (pathname === UI_BASE || pathname.startsWith(`${UI_BASE}/`))) {
    pathname = pathname.slice(UI_BASE.length) || "/";
  }
  try {
    if (req.method === "POST" && pathname === "/api/parse") {
      return await bridge(req, res, url);
    }

    if (req.method === "GET" && pathname === "/api/samples") {
      return sendJson(res, 200, { files: await listSamples() });
    }

    // A name may contain one `large/` segment, so the path is resolved and
    // then checked to be inside the sample directory rather than pattern
    // matched. Prefix checks on unresolved strings are how directory
    // traversal gets through.
    const sample = pathname.match(/^\/api\/samples\/(.+)$/);
    if (req.method === "GET" && sample) {
      const file = path.resolve(sampleDir, decodeURIComponent(sample[1]));
      if (!file.startsWith(sampleDir + path.sep)) {
        return sendJson(res, 403, { error: "outside the sample directory" });
      }
      const { size } = await stat(file);
      res.writeHead(200, {
        "content-type": "application/pdf",
        "content-length": size,
      });
      return res.end(await readFile(file));
    }

    // Static front end. no-store: this is a live demo page, never let the
    // browser run a stale copy of it. When a base is configured the page is
    // told about it through a meta tag, and prefixes its own calls with it.
    if (req.method === "GET" && (pathname === "/" || pathname === "/index.html")) {
      let html = await readFile(path.join(publicDir, "index.html"), "utf8");
      if (UI_BASE) {
        html = html.replace("</head>", `<meta name="ui-base" content="${UI_BASE}">\n</head>`);
      }
      res.writeHead(200, {
        "content-type": "text/html; charset=utf-8",
        "cache-control": "no-store",
      });
      return res.end(html);
    }
    if (req.method === "GET" && pathname === "/favicon.ico") {
      res.writeHead(204);
      return res.end();
    }

    sendJson(res, 404, { error: "not found" });
  } catch (err) {
    sendJson(res, 502, { error: err.details ?? err.message });
  }
});

server.on("error", (err) => {
  if (err.code === "EADDRINUSE") {
    console.error(`port ${PORT} is already in use, another bridge instance?`);
    console.error(`stop it, or run with a different port: PORT=8096 npm start`);
    process.exit(1);
  }
  throw err;
});

server.listen(PORT, () => {
  console.log(`grpc-pdf-inspector web demo on http://127.0.0.1:${PORT}${UI_BASE || "/"}`);
  console.log(`forwarding to grpc-pdf-inspector at ${ADDR}`);
});
